//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto_Cadimuns
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableDescription
    {
        public int Id { get; set; }
        public string TableId { get; set; }
        public string TableName { get; set; }
        public string ColumnName { get; set; }
        public int TypeColumn { get; set; }
        public Nullable<short> Precision { get; set; }
        public Nullable<short> Scale { get; set; }
        public bool Nullable { get; set; }
        public string MaxValue { get; set; }
        public string MinValue { get; set; }
        public bool IsOnlyNumber { get; set; }
        public bool DateTimeContainsHourMinuteSecond { get; set; }
    
        public virtual DataBase DataBase { get; set; }
    }
}
